force-app/main/default/objects/Data_Type_Setting__mdt/Data_Type_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Configuration for survey question data types</description>
    <label>Data Type Setting</label>
    <pluralLabel>Data Type Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Data_Type_Setting__mdt/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <description>Eligible value from the Data Types global value set</description>
    <inlineHelpText>Eligible value from the Data Types global value set</inlineHelpText>
    <label>Data Type</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Type_Setting__mdt/fields/Lightning_Input_Type__c.field-meta.xml
<CustomField>
    <fullName>Lightning_Input_Type__c</fullName>
    <description>The type of the input for a lightning input component. Valid values are checkbox, checkbox-button, color, date, datetime, time, email, file, password, range, search, tel, url, number, and toggle. This value defaults to text.</description>
    <inlineHelpText>The type of the input for a lightning input component. Valid values are checkbox, checkbox-button, color, date, datetime, time, email, file, password, range, search, tel, url, number, and toggle. This value defaults to text.</inlineHelpText>
    <label>Lightning Input Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DataTypesUtil_Test.cls
@IsTest
private class DataTypesUtil_Test {
    
    @IsTest
    static void testGetLightningInputType() {
        Data_Type_Setting__mdt setting = Data_Type_Setting__mdt.getAll().values().get(0);
        String lightningInputType;
        Test.startTest();
        lightningInputType = DataTypesUtil.getLightningInputType(setting.Data_Type__c);
        Test.stopTest();
        Assert.areEqual(setting.Lightning_Input_Type__c, lightningInputType, 'Received incorrect lightning input type');
    }

    @IsTest
    static void testGetDataTypeFromLightningInputType() {
        Data_Type_Setting__mdt setting = Data_Type_Setting__mdt.getAll().values().get(0);
        String strDataType;
        Test.startTest();
        strDataType = DataTypesUtil.getDataTypeFromLightningInputType(setting.Lightning_Input_Type__c);
        Test.stopTest();
        Assert.areEqual(setting.Data_Type__c, strDataType, 'Received incorrect data type');
    }

}