force-app/main/default/objects/Data_Type_Setting__mdt/Data_Type_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Configuration for survey question data types</description>
    <label>Data Type Setting</label>
    <pluralLabel>Data Type Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Data_Type_Setting__mdt/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <description>Eligible value from the Data Types global value set</description>
    <inlineHelpText>Eligible value from the Data Types global value set</inlineHelpText>
    <label>Data Type</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_Type_Setting__mdt/fields/Lightning_Input_Type__c.field-meta.xml
<CustomField>
    <fullName>Lightning_Input_Type__c</fullName>
    <description>The type of the input for a lightning input component. Valid values are checkbox, checkbox-button, color, date, datetime, time, email, file, password, range, search, tel, url, number, and toggle. This value defaults to text.</description>
    <inlineHelpText>The type of the input for a lightning input component. Valid values are checkbox, checkbox-button, color, date, datetime, time, email, file, password, range, search, tel, url, number, and toggle. This value defaults to text.</inlineHelpText>
    <label>Lightning Input Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DataTypesUtil.cls
public with sharing class DataTypesUtil {
    
    private static Map<String, Data_Type_Setting__mdt> mapDataTypes;
    private static Map<String, Data_Type_Setting__mdt> mapDataTypesByLightningInputType;

    public static String getLightningInputType(
        String dataType
    ) {
        if (mapDataTypes == null) {
            cacheDataTypeSettings();
        }
        return mapDataTypes.get(dataType)?.Lightning_Input_Type__c;
    }

    public static String getDataTypeFromLightningInputType(
        String lightningDataType
    ) {
        if (mapDataTypesByLightningInputType == null) {
            cacheDataTypeSettings();
        }
        return mapDataTypesByLightningInputType.get(lightningDataType)?.Data_Type__c;
    }

    private static void cacheDataTypeSettings() {
        mapDataTypes = new Map<String, Data_Type_Setting__mdt>();
        mapDataTypesByLightningInputType = new Map<String, Data_Type_Setting__mdt>();
        List<Data_Type_Setting__mdt> lstSettings = Data_Type_Setting__mdt.getAll().values();
        for (Data_Type_Setting__mdt dts : lstSettings) {
            mapDataTypes.put(dts.Data_Type__c, dts);
            mapDataTypesByLightningInputType.put(dts.Lightning_Input_Type__c, dts);
        }
    }

}