force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>A templated collection of survey questions</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Answer__c/Survey_Answer__c.object-meta.xml
<CustomObject>
    <description>An answer to a survey question</description>
    <label>Survey Answer</label>
    <nameField>
        <displayFormat>SA-{000000000}</displayFormat>
        <label>Survey Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Answer__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <description>The data type of the answer</description>
    <inlineHelpText>The data type of the answer</inlineHelpText>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Data_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Survey_Question__c.field-meta.xml
<CustomField>
    <fullName>Survey_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The question this answer responded to</description>
    <inlineHelpText>The question this answer responded to</inlineHelpText>
    <label>Survey Question</label>
    <referenceTo>Survey_Question__c</referenceTo>
    <relationshipLabel>Survey Answers</relationshipLabel>
    <relationshipName>Survey_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Survey_Response__c.field-meta.xml
<CustomField>
    <fullName>Survey_Response__c</fullName>
    <label>Survey Response</label>
    <referenceTo>Survey_Response__c</referenceTo>
    <relationshipLabel>Survey Answers</relationshipLabel>
    <relationshipName>Survey_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/Survey_Question__c.object-meta.xml
<CustomObject>
    <description>An individual survey question to collect responses for</description>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ-{000000}</displayFormat>
        <label>Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Question__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <description>The data type of the answer</description>
    <inlineHelpText>The data type of the answer</inlineHelpText>
    <label>Data Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Questions</relationshipLabel>
    <relationshipName>Survey_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/Survey_Response__c.object-meta.xml
<CustomObject>
    <description>A contact&apos;s response to a particular survey</description>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Survey Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Response__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Data_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Date</fullName>
    </customValue>
    <customValue>
        <fullName>Number</fullName>
    </customValue>
    <customValue>
        <fullName>Picklist</fullName>
    </customValue>
    <customValue>
        <fullName>Text</fullName>
    </customValue>
    <description>Supported data types for surveys</description>
    <masterLabel>Data Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CommunitySurveyController_Test.cls
@IsTest
private class CommunitySurveyController_Test {

    @TestSetup
    static void makeData() {
        User u = TestDataFactory.createUser('Admin');

        System.runAs(u) {
            Survey__c survey = TestDataFactory.createSurveys(
                1, 
                true
            ).get(0);

            List<Survey_Question__c> lstQuestions = TestDataFactory.createSurveyQuestions(
                survey.Id, 
                5, 
                true
            );

            Contact ct = TestDataFactory.createContacts(
                1, 
                true
            ).get(0);
        }

    }

    @IsTest 
    static void testInitializeSurvey() {
        User adminUser = [
            SELECT Id 
              FROM User 
             WHERE Id IN (SELECT AssigneeId FROM PermissionSetAssignment WHERE PermissionSet.Name = 'Surveys_Admin')
             LIMIT 1
        ];
        Survey__c survey = [
            SELECT Id, 
                   (SELECT Id FROM Survey_Questions__r) 
              FROM Survey__c 
             LIMIT 1
        ];
        List<CommunitySurveyController.SurveyQuestionWrapper> lstWrappers;
        Test.startTest();
        System.runAs(adminUser) {
            lstWrappers = CommunitySurveyController.initializeSurvey(
                survey.Id
            );
        }
        Test.stopTest();
        Assert.areEqual(
            survey.Survey_Questions__r.size(), 
            lstWrappers.size(), 
            'Should have received an answer for every question'
        );
    }

    @IsTest
    static void testSubmitSurvey() {
        User adminUser = [
            SELECT Id 
              FROM User 
             WHERE Id IN (SELECT AssigneeId FROM PermissionSetAssignment WHERE PermissionSet.Name = 'Surveys_Admin')
             LIMIT 1
        ];
        
        Survey__c survey = [
            SELECT Id, 
                   (SELECT Id FROM Survey_Questions__r) 
              FROM Survey__c 
             LIMIT 1
        ];

        Contact ct = [SELECT Id FROM Contact LIMIT 1];

        Id surveyResponseId;

        Test.startTest();
        System.runAs(adminUser) {
            List<Survey_Answer__c> lstAnswers = new List<Survey_Answer__c>();
            List<CommunitySurveyController.SurveyQuestionWrapper> lstWrappers;
            lstWrappers = CommunitySurveyController.initializeSurvey(
                survey.Id
            );

            for (CommunitySurveyController.SurveyQuestionWrapper q : lstWrappers) {
                lstAnswers.add(
                    new Survey_Answer__c(
                        Survey_Question__c = q.id,
                        Question__c = q.question,
                        Data_Type__c = q.dataType,
                        Answer__c = 'Test Answer'
                    )
                );
            }
        
            surveyResponseId = CommunitySurveyController.submitSurvey(
                survey.Id, 
                ct.Id, 
                lstAnswers
            );
        }
        Test.stopTest();

        Survey_Response__c response = [
            SELECT Id,
                   (SELECT Id FROM Survey_Answers__r)
              FROM Survey_Response__c
             WHERE Id = :surveyResponseId
             LIMIT 1
        ];

        Assert.areEqual(
            survey.Survey_Questions__r.size(), 
            response.Survey_Answers__r.size(), 
            'Should have received an answer for every question'
        );
    }

}