force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>A templated collection of survey questions</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Answer__c/Survey_Answer__c.object-meta.xml
<CustomObject>
    <description>An answer to a survey question</description>
    <label>Survey Answer</label>
    <nameField>
        <displayFormat>SA-{000000000}</displayFormat>
        <label>Survey Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Answer__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <description>The data type of the answer</description>
    <inlineHelpText>The data type of the answer</inlineHelpText>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Data_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Help_Text__c</fullName>
    <description>The help text at the time the question was answered</description>
    <inlineHelpText>The help text at the time the question was answered</inlineHelpText>
    <label>Help Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Survey_Question__c.field-meta.xml
<CustomField>
    <fullName>Survey_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The question this answer responded to</description>
    <inlineHelpText>The question this answer responded to</inlineHelpText>
    <label>Survey Question</label>
    <referenceTo>Survey_Question__c</referenceTo>
    <relationshipLabel>Survey Answers</relationshipLabel>
    <relationshipName>Survey_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Answer__c/fields/Survey_Response__c.field-meta.xml
<CustomField>
    <fullName>Survey_Response__c</fullName>
    <label>Survey Response</label>
    <referenceTo>Survey_Response__c</referenceTo>
    <relationshipLabel>Survey Answers</relationshipLabel>
    <relationshipName>Survey_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/Survey_Question__c.object-meta.xml
<CustomObject>
    <description>An individual survey question to collect responses for</description>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ-{000000}</displayFormat>
        <label>Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Question__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <description>The data type of the answer</description>
    <inlineHelpText>The data type of the answer</inlineHelpText>
    <label>Data Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Help_Text__c</fullName>
    <description>Help text to present to the user when encountering this field in a survey</description>
    <inlineHelpText>Help text to present to the user when encountering this field in a survey</inlineHelpText>
    <label>Help Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Hidden__c.field-meta.xml
<CustomField>
    <fullName>Hidden__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, users will not be able to see this survey question when responding to the survey</description>
    <inlineHelpText>If checked, users will not be able to see this survey question when responding to the survey</inlineHelpText>
    <label>Hidden</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, this field must be completed prior to submission</description>
    <inlineHelpText>If checked, this field must be completed prior to submission</inlineHelpText>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>The order in which this question should appear in the survey. Lowest numbers appear first. Nulls last.</description>
    <inlineHelpText>The order in which this question should appear in the survey. Lowest numbers appear first. Nulls last.</inlineHelpText>
    <label>Sort Order</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Survey_Question__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Questions</relationshipLabel>
    <relationshipName>Survey_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/Survey_Response__c.object-meta.xml
<CustomObject>
    <description>A contact&apos;s response to a particular survey</description>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Survey Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Response__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey_Response__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Data_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Date</fullName>
    </customValue>
    <customValue>
        <fullName>Number</fullName>
    </customValue>
    <customValue>
        <fullName>Picklist</fullName>
    </customValue>
    <customValue>
        <fullName>Text</fullName>
    </customValue>
    <description>Supported data types for surveys</description>
    <masterLabel>Data Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CommunitySurveyController.cls
public with sharing class CommunitySurveyController {
    
    /***************************************************
     * Get new survey response with survey answers
     * @param String recordId - Survey ID
     * @return Survey_Question__c[] collection of survey questions
     ***************************************************/
    @AuraEnabled(cacheable=true)
    public static List<SurveyQuestionWrapper> initializeSurvey(
        String recordId
    ) {
        List<SurveyQuestionWrapper> lstWrappers = new List<SurveyQuestionWrapper>();
        for (Survey_Question__c q : getSurveyQuestions(recordId)) {
            SurveyQuestionWrapper qWrap = new SurveyQuestionWrapper();
            qWrap.id = q.Id;
            qWrap.sortOrder = q.Sort_Order__c;
            qWrap.dataType = DataTypesUtil.getLightningInputType(q.Data_Type__c);
            qWrap.question = q.Question__c;
            qWrap.helpText = q.Help_Text__c;
            qWrap.isRequired = q.Required__c;
            qWrap.isHidden = q.Hidden__c;
            lstWrappers.add(qWrap);
        }
        return lstWrappers;
    }

    /************************************************************************
     * Save survey response and child survey answers
     * @param sObject[] records - Collection of answer objects to save
     * @return Id - Survey response id
     ************************************************************************/

     @AuraEnabled(cacheable=false)
     public static Id submitSurvey(
        String recordId, 
        String contactId, 
        List<sObject> answers
     ) {
        try {
            Survey_Response__c sr = new Survey_Response__c();
            sr.Survey__c = recordId;
            sr.Contact__c = contactId;
            Database.insert(
                sr, 
                false, 
                AccessLevel.USER_MODE
            );

            // Cast generic sObject to list of application answers
            List<Survey_Answer__c> lstAnswers = (List<Survey_Answer__c>) answers;
            for (Survey_Answer__c ans : lstAnswers) {
                ans.Survey_Response__c = sr.Id;
                // Convert lightning data type back to valid picklist value
                ans.Data_Type__c = DataTypesUtil.getDataTypeFromLightningInputType(ans.Data_Type__c);
            }

            // Update application answers
            Database.insert(
                lstAnswers,
                false,
                AccessLevel.USER_MODE
            );
            return sr.Id;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    private static List<Survey_Question__c> getSurveyQuestions(
        String surveyId
    ) {
        return [
            SELECT Id,
                   Question__c,
                   Sort_Order__c,
                   Data_Type__c,
                   Help_Text__c,
                   Required__c,
                   Hidden__c
              FROM Survey_Question__c 
             WHERE Survey__c = :surveyId 
             ORDER BY Sort_Order__c ASC
             LIMIT 10000
        ];
    }

    /************************************************************************
     * Save survey response and child survey answers
     * @param sObject[] records - Collection of answer objects to save
     * @return Id - Survey response id
     ************************************************************************/

    public class SurveyQuestionWrapper {
        @AuraEnabled
        public Id id {get;set;}
        @AuraEnabled
        public Decimal sortOrder {get;set;}
        @AuraEnabled
        public String dataType {get;set;}
        @AuraEnabled
        public String question {get;set;}
        @AuraEnabled
        public String helpText {get;set;}
        @AuraEnabled
        public Boolean isRequired {get;set;}
        @AuraEnabled
        public Boolean isHidden {get;set;}
    }

}